### ISSUE TITLE
Voteable Github Issue Structure

### ISSUE THREAD

**Issue by wip-abramson** [commons-stack/genesis-frontend#3]
What is the data that we require from a Github Issue for it to be voted on?

**Comment by Joshfairhead** [comment]
Title, ticket number/URI and body would be good minimal first steps I reckon. After that it depends on lots of things, but keeping things as LEAN as possible for now would be my preference. Once a super basic MVP is built and we get a smell of the first iteration we'll figure out the next tensions to address on refactor. 

We probably wanna hear from a more diverse set of voices though; so let's see what Sponnet, Kay, Dani and Marko think for starters.

**Comment by wip-abramson** [comment]
I mean the issues that we pull in and list in https://genesis.commons-stack.tk/

Currently the just store the funding amount. But I think it may be worth extending this to include dummy conviction data about each issue.

**Comment by wip-abramson** [comment]
I would like to include information like this in each github issue for now:

const convictions = [
    {
        name: "Philadelphia DAO",
        stakes: [
            { time: around(0), tokensStaked: around(2000, 300) },
            { time: around(50), tokensStaked: around(0, 300) }
        ]
    },
    {
        name: "Aqua Array",
        stakes: [
            { time: around(20), tokensStaked: around(333, 300) },
            { time: around(65), tokensStaked: around(6000, 5000) }
        ]
    },
    {
        name: "Global Water Commons",
        stakes: [
            { time: around(30), tokensStaked: around(1000, 500) },
            { time: around(80), tokensStaked: around(7000, 4500) }
        ]
    },
    {
        name: "Autofactory Factory",
        stakes: [
            { time: around(0), tokensStaked: 1100 },
            { time: around(30), tokensStaked: 7000 }
        ]
    }
];
